version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ouroboros
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    container_name: ouroboros
    build: .
    depends_on:
      - db
    ports:
      - 8000:8000
    command: python manage.py runserver --settings=ouroboros.settings.docker_dev 0.0.0.0:8000
    volumes:
      - resume_storage:/resumes

volumes: 
  resume_storage:
  postgres-data: