# Generated by Django 2.2.13 on 2021-01-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0048_auto_20210111_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='agree_to_discord_rules',
            field=models.BooleanField(choices=[(True, 'Agree'), (False, 'Disagree')], null=True, verbose_name='I agree to the rules shown above.'),
        ),
    ]
