# Generated by Django 2.2.13 on 2021-01-20 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0049_application_agree_to_discord_rules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='agree_to_discord_rules',
        ),
    ]
