# Generated by Django 2.2.13 on 2021-01-25 21:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0050_remove_application_agree_to_discord_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='school_email',
            field=models.CharField(help_text='Please enter your school address ending in .edu to be considered. Contact us at team@hacklahoma.org for any exceptions.', max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid email address ending in .edu', regex='^([A-Za-z0-9_\\.-]+\\@([\\da-z\\.-]+\\.(edu|ie|edu\\.in|ac\\.in|unam\\.mx)|ontariotechu\\.net)|shizhe\\.he6\\@gmail\\.com|arjun110503\\@gmail\\.com|m11dedhia\\@gmail\\.com)$')], verbose_name='email address'),
        ),
    ]
