# Generated by Django 2.2.13 on 2021-02-01 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0051_auto_20210125_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='school_email',
            field=models.CharField(help_text='Please enter your school address ending in .edu to be considered. Contact us at team@hacklahoma.org for any exceptions.', max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid email address ending in .edu', regex='^([A-Za-z0-9_\\.-]+\\@([\\da-z\\.-]+\\.(edu|ie|edu\\.in|ac\\.in|unam\\.mx|ca)|ontariotechu\\.net)|shizhe\\.he6\\@gmail\\.com|arjun110503\\@gmail\\.com|m11dedhia\\@gmail\\.com|b2j1999jan27\\@gmail\\.com|gilvinokunimah\\@gmail\\.com|k9981zhu\\@gmail\\.com|kamathsrikant\\@gmail\\.com|prahitha.movva03\\@gmail\\.com|deveshrajput978\\@gmail\\.com|sanchitbanati33\\@gmail\\.com)$')], verbose_name='email address'),
        ),
    ]
